#ifndef INCLUDE_BLE_EVENTS_H_
#define INCLUDE_BLE_EVENTS_H_

#include <ble.h>
#include <bsp.h>
#include <ble_advertising.h>

#include <ble.h>
#include <bsp.h>
#include <ble_advertising.h>

uint16_t m_conn_handle; /**< Handle of the current connection. */

/**@brief Function for dispatching a BLE stack event to all modules with a BLE stack event handler.
 *
 * @details This function is called from the BLE Stack event interrupt handler after a BLE stack
 *          event has been received.
 *
 * @param[in] p_ble_evt  Bluetooth stack event.
 */
extern void ble_evt_dispatch(ble_evt_t * p_ble_evt);

/**@brief Function for dispatching a system event to interested modules.
 *
 * @details This function is called from the System event interrupt handler after a system
 *          event has been received.
 *
 * @param[in] sys_evt  System stack event.
 */
extern void sys_evt_dispatch(uint32_t sys_evt);

/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by button press.
 */
extern void bsp_event_handler(bsp_event_t event);

/**@brief Function for handling advertising events.
 *
 * @details This function will be called for advertising events which are passed to the application.
 *
 * @param[in] ble_adv_evt  Advertising event.
 */
extern void on_adv_evt(ble_adv_evt_t ble_adv_evt);

#endif